-- ===========================================================================
-- Call recordings + follow-up tickets
-- ===========================================================================

-- Recording URL so staff can listen to each call.
alter table public.calls add column if not exists recording_url text;

-- Tickets: one follow-up ticket auto-created per call (webhook + manual sync).
create table if not exists public.tickets (
  id                  uuid primary key default gen_random_uuid(),
  number              bigint generated by default as identity,
  vapi_call_id        text unique,
  master_bill_number  text,
  subject             text not null,
  category            text,                            -- mirrors call detected_intent
  priority            text not null default 'normal',  -- low | normal | high
  status              text not null default 'open',    -- open | closed
  description         text,
  created_at          timestamptz not null default now()
);

create index if not exists tickets_status_idx on public.tickets (status);
create index if not exists tickets_created_at_idx on public.tickets (created_at desc);

alter table public.tickets enable row level security;

do $$
begin
  create policy "auth read tickets"   on public.tickets
    for select to authenticated using (true);
  create policy "auth update tickets" on public.tickets
    for update to authenticated using (true) with check (true);
exception
  when duplicate_object then null;
end
$$;
